In [1]:
import math

# {:^3} şu manaya geliyor. 3 karakterlik bir yer aç ve yazacağın metni ortala
# {:>3} şu manaya geliyor. 3 karakterlik bir yer aç ve yazacağın metni sağa yasla
# {:<3} şu manaya geliyor. 3 karakterlik bir yer aç ve yazacağın metni sola yasla

print ('{:^3}  {:^6}  {:^6}  {:^6}'.format('e', 'x', 'x**2', 'isinf'))
print ('{:-^3}  {:-^6}  {:-^6}  {:-^6}'.format('', '', '', ''))

for e in range(0, 201, 10):
    x = 10.0 ** e
    y = x*x
    print ('{:3d}  {!s:6}  {!s:6}  {!s:6}'.format(e, x, y, math.isinf(y)))

 e     x      x**2   isinf 
---  ------  ------  ------
  0  1.0     1.0     False 
 10  10000000000.0  1e+20   False 
 20  1e+20   1e+40   False 
 30  1e+30   1.0000000000000001e+60  False 
 40  1e+40   1e+80   False 
 50  1e+50   1.0000000000000002e+100  False 
 60  1e+60   9.999999999999998e+119  False 
 70  1e+70   1e+140  False 
 80  1e+80   1e+160  False 
 90  1e+90   9.999999999999999e+179  False 
100  1e+100  1e+200  False 
110  1e+110  1e+220  False 
120  1e+120  1e+240  False 
130  1e+130  1e+260  False 
140  1e+140  1e+280  False 
150  1e+150  9.999999999999999e+299  False 
160  1e+160  inf     True  
170  1e+170  inf     True  
180  1e+180  inf     True  
190  1e+190  inf     True  
200  1e+200  inf     True  


In [5]:
import math

print ('{:>7}  {:>7}  {:>7}'.format('x', 'm', 'e'))
print ('{:-^7}  {:-^7}  {:-^7}'.format('', '', ''))

# frexp() fonksiyonu x = m * 2**e formülü uyarınca 
# verilen x değeri için m ve e değerlerini döndürür

for x in [ 0.01, 0.1, 0.5, 1.0, 2.0, 3.0, 4.0, 5.0]:
    m, e = math.frexp(x)
    print ('{:7.2f}  {:7.2f}  {:7d}'.format(x, m, e))

      x        m        e
-------  -------  -------
   0.01     0.64       -6
   0.10     0.80       -3
   0.50     0.50        0
   1.00     0.50        1
   2.00     0.50        2
   3.00     0.75        2
   4.00     0.50        3
   5.00     0.62        3


In [11]:
import math

degerler = [ 0.1 ] * 10

print ('Girdi Değerleri:', degerler)

# built-in sum() fonksiyonu ile hesaplama 
print ('sum() fonksiyonu çıktısı       : {:.20f}'.format(sum(degerler)))

# for döngüsü ile yapılan hesaplama 
toplam = 0.0
for indeks in degerler:
    toplam += indeks
print ('for döngüsü çıktısı            : {:.20f}'.format(toplam))
    
# math modülü içerisindeki fsum() fonksiyonu ile hesaplama 
print ('math.fsum() fonksiyonu çıktısı : {:.20f}'.format(math.fsum(degerler)))

Girdi Değerleri: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
sum() fonksiyonu çıktısı       : 0.99999999999999988898
for döngüsü çıktısı            : 0.99999999999999988898
math.fsum() fonksiyonu çıktısı : 1.00000000000000000000


In [12]:
import math

print ('{:2}  {:^12}  {:^20}  {:^20}  {:8}'.format('i', 'x', 'doğru', 'az doğru', 'uyumsuzluk'))
print ('{:-^2}  {:-^12}  {:-^20}  {:-^20}  {:-^8}'.format('', '', '', '', ''))

for indeks in range(0, 10):
    x = math.pow(10, indeks)
    dogru_deger = math.log10(x)    # 10 tabanında logaritma fonksiyonu
    az_dogru_deger = math.log(x, 10)   # genel logaritma fonksiyonunu taban = 10 olacak şekilde
    
    if int(az_dogru_deger) == indeks:
        uyumsuzluk = ''
    else:
        uyumsuzluk = '*'
    # aynı if/else ifadesini, alternatif olarak tek satırda da yazabilirdik. Şu şekilde: 
    # uyumsuzluk = '' if int(az_dogru_deger) == indeks else '*'
    
    print ('{:2d}  {:12.1f}  {:20.18f}  {:20.18f}  {:^5}'.format(indeks, x, dogru_deger, az_dogru_deger, uyumsuzluk))
    

i        x               doğru                az doğru        uyumsuzluk
--  ------------  --------------------  --------------------  --------
 0           1.0  0.000000000000000000  0.000000000000000000       
 1          10.0  1.000000000000000000  1.000000000000000000       
 2         100.0  2.000000000000000000  2.000000000000000000       
 3        1000.0  3.000000000000000000  2.999999999999999556    *  
 4       10000.0  4.000000000000000000  4.000000000000000000       
 5      100000.0  5.000000000000000000  5.000000000000000000       
 6     1000000.0  6.000000000000000000  5.999999999999999112    *  
 7    10000000.0  7.000000000000000000  7.000000000000000000       
 8   100000000.0  8.000000000000000000  8.000000000000000000       
 9  1000000000.0  9.000000000000000000  8.999999999999998224    *  


In [19]:
import math

print ('Derece   Radyan   Sinüs    Kosinüs   Tanjant')
print ('-------  -------  -------  --------  -------')

fmt = '  '.join(['%7.2f'] * 5)

for derece in range(0, 361, 30):
    radyan = math.radians(derece)
    if derece in (90, 270):
        tanjant = float('inf')
    else:
        tanjant = math.tan(radyan)
    print (fmt % (derece, radyan, math.sin(radyan), math.cos(radyan), tanjant))

Derece   Radyan   Sinüs    Kosinüs   Tanjant
-------  -------  -------  --------  -------
   0.00     0.00     0.00     1.00     0.00
  30.00     0.52     0.50     0.87     0.58
  60.00     1.05     0.87     0.50     1.73
  90.00     1.57     1.00     0.00      inf
 120.00     2.09     0.87    -0.50    -1.73
 150.00     2.62     0.50    -0.87    -0.58
 180.00     3.14     0.00    -1.00    -0.00
 210.00     3.67    -0.50    -0.87     0.58
 240.00     4.19    -0.87    -0.50     1.73
 270.00     4.71    -1.00    -0.00      inf
 300.00     5.24    -0.87     0.50    -1.73
 330.00     5.76    -0.50     0.87    -0.58
 360.00     6.28    -0.00     1.00    -0.00


In [1]:
import numpy as np

In [2]:
x = [2, 3, 4, 5, 6]
print(x)

[2, 3, 4, 5, 6]


In [3]:
y = x + 10

TypeError: can only concatenate list (not "int") to list

In [7]:
x = [2, 3, 4, 5, 6]
print(x)
y = [a + 10 for a in x]
print(y)

[2, 3, 4, 5, 6]
[12, 13, 14, 15, 16]


In [8]:
ilk_liste = np.array([2, 3, 4, 5, 6])
print(ilk_liste)
ikinci_liste = ilk_liste + 10
print(ikinci_liste)

[2 3 4 5 6]
[12 13 14 15 16]


In [9]:
yeni_liste = np.array([[2,3,4],[5,6,7],[8,9,10]])
print(yeni_liste)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [11]:
yepyeni_liste = np.arange(17, 2, -2)
print(yepyeni_liste)

[17 15 13 11  9  7  5  3]


In [12]:
sifir_listesi = np.zeros(5)
print(sifir_listesi)

[0. 0. 0. 0. 0.]


In [13]:
bir_listesi = np.ones(5)
print(bir_listesi)

[1. 1. 1. 1. 1.]


In [15]:
sifir_listesi2 = np.zeros((5,4))
print(sifir_listesi2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
lineer = np.linspace(1, 10, 21)
print(lineer)

[ 1.    1.45  1.9   2.35  2.8   3.25  3.7   4.15  4.6   5.05  5.5   5.95
  6.4   6.85  7.3   7.75  8.2   8.65  9.1   9.55 10.  ]


In [4]:
logaritmik = np.logspace(-3, 3, 7)
print(logaritmik)

[1.e-03 1.e-02 1.e-01 1.e+00 1.e+01 1.e+02 1.e+03]


In [20]:
birim_matris = np.eye(5)
print(birim_matris)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [25]:
rastgele_dizi = np.random.rand(5,4) # her biri 0-1 arasında düzgün dağılıma uygun rastgele sayı
print(rastgele_dizi)

[[0.90794215 0.66798374 0.70963244 0.21103285]
 [0.10248869 0.39727241 0.30985227 0.97983939]
 [0.53016944 0.55382961 0.29102901 0.64500587]
 [0.46855102 0.12355264 0.85775976 0.14123159]
 [0.3145649  0.39628827 0.5287441  0.68924733]]


In [26]:
rastgele_dizi2 = np.random.randn(2,3) # her biri, ortalaması 0 ve std. sapması 1'e eşit Gauss dağılımına uygun rastgele sayı
print(rastgele_dizi2)


[[ 3.89949013e-04  6.49944997e-01  8.01005092e-02]
 [-1.16530697e+00  8.70785796e-01  3.30162668e-01]]


In [28]:
rastgele_dizi3 = 30 + (5 * np.random.randn(2,3)) 
# her biri, ortalaması 30 ve std. sapması 5'e eşit Gauss dağılımına uygun rastgele sayı
print(rastgele_dizi3)


[[35.64255224 35.87440789 27.77157513]
 [28.73179351 24.05041513 31.96873953]]


In [29]:
rastgele_dizi4 = np.random.randint(50, 100, 5) # her biri 50 ile 100 arasında düzgün dağılıma uyan tam sayı 
print(rastgele_dizi4) 

[87 75 99 85 76]


In [2]:
import numpy as np
matrisimiz = np.arange(1,17)
print(matrisimiz)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [6]:
matrisimiz2 = matrisimiz.reshape(8,2)
print(matrisimiz2)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]


In [12]:
rastgele_matris = np.random.randint(1, 100, 10)
print(rastgele_matris)

[66 88 59 47 62 70 57  6 17 45]


In [13]:
minimum_deger = rastgele_matris.min()
print(minimum_deger)
print(rastgele_matris.argmin())
maksimum_deger = rastgele_matris.max()
print(maksimum_deger)
print(rastgele_matris.argmax())


6
7
88
1


In [14]:
print(rastgele_matris[2])

59


In [15]:
print(rastgele_matris[2:5])

[59 47 62]


In [16]:
rastgele_alt_matris = rastgele_matris[2:5]
print(rastgele_alt_matris)

[59 47 62]


In [18]:
iki_boyutlu_dizi = np.array(([1,2,3],[4,5,6],[7,8,9]))
print(iki_boyutlu_dizi)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
print(iki_boyutlu_dizi[2,2])

9


In [20]:
print(iki_boyutlu_dizi[:,2])

[3 6 9]


In [21]:
print(iki_boyutlu_dizi[1,:])

[4 5 6]


In [22]:
print(iki_boyutlu_dizi[:2,:2])

[[1 2]
 [4 5]]


In [27]:
ilk_dizi = np.arange(1,17,1)
ikinci_dizi = np.arange(17,1,-1)
print(ilk_dizi)
print(ikinci_dizi)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2]


In [28]:
ucuncu_dizi = ilk_dizi + ikinci_dizi
print(ucuncu_dizi)

[18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18]


In [29]:
dorduncu_dizi = ilk_dizi + 25
print(dorduncu_dizi)

[26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41]


In [30]:
log_ilk_dizi = np.log(ilk_dizi)
print(log_ilk_dizi)

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509 2.39789527 2.48490665
 2.56494936 2.63905733 2.7080502  2.77258872]


In [31]:
exp_ilk_dizi = np.exp(ilk_dizi)
print(exp_ilk_dizi)

[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04 5.98741417e+04 1.62754791e+05
 4.42413392e+05 1.20260428e+06 3.26901737e+06 8.88611052e+06]


In [32]:
kok_ilk_dizi = np.sqrt(ilk_dizi)
print(kok_ilk_dizi)

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766 3.31662479 3.46410162
 3.60555128 3.74165739 3.87298335 4.        ]


In [33]:
sin_ilk_dizi = np.sin(ilk_dizi)
print(sin_ilk_dizi)

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111 -0.99999021 -0.53657292
  0.42016704  0.99060736  0.65028784 -0.28790332]


In [39]:
carp_ilk_dizi = ilk_dizi // 2
print(carp_ilk_dizi)

[0 1 1 2 2 3 3 4 4 5 5 6 6 7 7 8]


In [42]:
print(ilk_dizi)
print(ikinci_dizi)
dizi_carpimi = ilk_dizi * ikinci_dizi
print(dizi_carpimi)
print(dizi_carpimi.sum())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2]
[17 32 45 56 65 72 77 80 81 80 77 72 65 56 45 32]
952


In [43]:
print(ilk_dizi.dot(ikinci_dizi))

952


In [2]:
import numpy as np
X = np.array(([1,2,3],[4,5,6]))  # X, 2x3'lük bir matris
Y = np.array(([1,2],[4,5],[7,8])) # Y, 3x2'lik bir matris
print(X)
print(Y)


[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]
 [7 8]]


In [3]:
Z = np.dot(X,Y)    # hakiki matris çarpımı
print(Z)

[[30 36]
 [66 81]]


In [4]:
W = np.multiply(X,Y)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [6]:
W = np.multiply(X,X)  # Hadamard çarpımı (entry-wise çarpım)
print(W)

[[ 1  4  9]
 [16 25 36]]


In [12]:
kare_matris = np.array(([1,2],[3,4]))
print(kare_matris)
ters = np.linalg.inv(kare_matris)
print(ters)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [8]:
dogrulama = kare_matris.dot(ters)
print(dogrulama)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [9]:
determinant_degeri = np.linalg.det(kare_matris)
print(determinant_degeri)

-2.0000000000000004


In [11]:
trace_degeri = np.trace(kare_matris)
print(trace_degeri)

5


In [8]:
import numpy as np

dizimiz = np.array([4,5,6,7])
print(dizimiz)

[4 5 6 7]


In [9]:
print(dizimiz.ndim)

1


In [10]:
print(dizimiz.itemsize)

4


In [15]:
print(dizimiz.dtype)

int64


In [11]:
print(dizimiz.size)

4


In [12]:
print(dizimiz.shape)

(4,)


In [20]:
import numpy as np 
a = np.array([1.0, 5.55, 123, 0.567, 25.532]) 

print ('Original array:') 
print (a) 
print ('\n')  

print ('After rounding:') 
print (np.around(a)) 
print (np.around(a, decimals = 1)) 
print (np.around(a, decimals = 2)) 
print (np.around(a, decimals = -1))

Original array:
[  1.      5.55  123.      0.567  25.532]


After rounding:
[  1.   6. 123.   1.  26.]
[  1.    5.6 123.    0.6  25.5]
[  1.     5.55 123.     0.57  25.53]
[  0.  10. 120.   0.  30.]


In [22]:
a = np.array([0.25, 1.33, 1, 0, 100]) 
b = np.reciprocal(a)
print(b)

[4.        0.7518797 1.              inf 0.01     ]


<ipython-input-22-79386b8bc9ee>:2: RuntimeWarning: divide by zero encountered in reciprocal
  b = np.reciprocal(a)


In [26]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
c = np.power(a,b)
print(c)




[   10   400 27000]


In [27]:
import numpy as np 
a = np.array([-5.6j, 0.2j, 11. , 1+1j]) 

print (a) 

print ("a'nın reel kısmı")
print (np.real(a)) 

print ("a'nın imajiner kısmı") 
print (np.imag(a)) 

print ("a'nın karmaşık eşleniği") 
print (np.conj(a)) 

print ("a'nın argümanı (radyan cinsinden)") 
print (np.angle(a)) 

print ("a'nın argümanı (derece cinsinden)") 
print (np.angle(a, deg = True))

[-0.-5.6j  0.+0.2j 11.+0.j   1.+1.j ]
a'nın reel kısmı
[-0.  0. 11.  1.]
a'nın imajiner kısmı
[-5.6  0.2  0.   1. ]
a'nın karmaşık eşleniği
[-0.+5.6j  0.-0.2j 11.-0.j   1.-1.j ]
a'nın argümanı (radyan cinsinden)
[-1.57079633  1.57079633  0.          0.78539816]
a'nın argümanı (derece cinsinden)
[-90.  90.   0.  45.]


In [30]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]]) 

print ('Dizimiz:') 
print (a)  

print ('amin() uygulandığında:') 
print (np.amin(a,1)) # satır satır bak ve her bir satırın minimumunu döndür

print ('amin() yine uygulandığında') 
print (np.amin(a,0)) # sütun sütun bak ve her bir sütunun minimumunu döndür

print ('amin() parametresiz uygulandığında:')  
print (np.amin(a)) # tüm matrisin minimumunu bul

print ('amin() axis = 1 ile uygulandığında:') 
print (np.amin(a, axis = 1)) # satır satır bak ve her bir satırın minimumunu döndür

print ('amin() axis = 0 ile uygulandığında:') 
print (np.amin(a, axis = 0)) # sütun sütun bak ve her bir sütunun minimumunu döndür

# bütün bunlar amax için de geçerli

Dizimiz:
[[3 7 5]
 [8 4 3]
 [2 4 9]]
amin() uygulandığında:
[3 3 2]
amin() yine uygulandığında
[2 4 3]
amin() parametresiz uygulandığında:
2
amin() axis = 1 ile uygulandığında:
[3 3 2]
amin() axis = 0 ile uygulandığında:
[2 4 3]


In [31]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]]) 

print ("Dizimiz:") 
print (a) 

print ('ptp() uyguladığımızda:') 
print (np.ptp(a)) # tüm matrise bak ve matris bazında (max - min) değerini döndür

print ('ptp() fonksiyonunu axis = 1 boyunca uyguladığımızda:')  
print (np.ptp(a, axis = 1)) # satır satır bak ve satır bazında (max - min) değerini döndür

print ('ptp() fonksiyonunu axis = 0 boyunca uyguladığımızda:')  
print (np.ptp(a, axis = 0)) # sütun sütun bak ve sütun bazında (max - min) değerini döndür

Dizimiz:
[[3 7 5]
 [8 4 3]
 [2 4 9]]
ptp() uyguladığımızda:
7
ptp() fonksiyonunu axis = 1 boyunca uyguladığımızda:
[4 5 7]
ptp() fonksiyonunu axis = 0 boyunca uyguladığımızda:
[6 3 6]


In [32]:
a = np.array([[30,65,70],[80,95,10],[50,90,60]]) 

print ("Dizimiz: ")
print (a) 

print ("Tüm dizinin ortancası: ") 
print (np.median(a)) 

print ("Ortancayı axis = 0 ile hesaplarsak:")
print (np.median(a, axis = 0)) # sütun sütun bakıp her bir sütunun ortancasını hesapla

print ("Ortancayı axis = 1 ile hesaplarsak:")
print (np.median(a, axis = 1)) # satır satır bakıp her bir satırın ortancasını hesapla


Dizimiz: 
[[30 65 70]
 [80 95 10]
 [50 90 60]]
Tüm dizinin ortancası: 
65.0
Ortancayı axis = 0 ile hesaplarsak:
[50. 90. 60.]
Ortancayı axis = 1 ile hesaplarsak:
[65. 80. 60.]


In [33]:
a = np.array([1,2,3,4]) 

print ("Dizimiz:")
print (a) 

print ("Herhangi bir ağırlık belirtmezsek:") 
print (np.average(a)) 

agirlik = np.array([4,3,2,1]) 

print ("Ağırlık belirterek (ama True demeden) hesaplatırsak:") 
print (np.average(a, weights = agirlik)) # ağırlıklı ortalama hesapladı!...

print ("Ağırlık belirterek (ama True diyerek) hesaplatırsak:") 
print (np.average(a, weights = agirlik, returned = True))  # ağırlıklı ortalamanın yanı sıra ağırlıklar toplamını da hesapladı

Dizimiz:
[1 2 3 4]
Herhangi bir ağırlık belirtmezsek:
2.5
Ağırlık belirterek (ama True demeden) hesaplatırsak:
2.0
Ağırlık belirterek (ama True diyerek) hesaplatırsak:
(2.0, 10.0)
